### PR TITLE
Build fixed and GitHub actions

### PR DESCRIPTION
**Pull request by andrewleech**
Hi, thanks for building this awesome open source editor for Android!

I ran into some issues building it from a clean git clone which I've addressed in the first couple I of commits here, do they look right to you?

I also added a yarn/npm target for a shortcut to reset the git repo to a clean state; this just deletes all the ignored files (build state / artifacts) to make it easier to test if the build is working reliably.

I then got GitHub actions set up to try to make the build more repeatable long term. The run from this branch can be seen here: https://github.com/andrewleech/Acode/actions/runs/3660345162

### CODE REVIEW

**Comment by andrewleech** [comment]
In case it's of any interest to anyone, I was using the following script to build this project locally. The bulk of it is done in a docker environment to ensure tool version control.
``` bash
docker run -t --rm -v $(pwd):/Acode -w /Acode hamdifourati/cordova-android-builder:cordova-11 bash -c '\
yes | sdkmanager --licenses ;\
chown -R root . ;\
npm add -g yarn ;\
yarn setup ;\
cordova telemetry on ;\
yarn clean ;\
npm run build android paid prod ;\
npm run build android paid d ;\
chown -R 1000 . ;\
'

## convert aab bundle to APK

# grab tool for conversion
if [  ! -f bundletool-all-1.13.1.jar ]; then
  wget https://github.com/google/bundletool/releases/download/1.13.1/bundletool-all-1.13.1.jar
fi

# generate signature
if [  ! -f acode.keystore ]; then
keytool -genkey -v -keystore acode.keystore -alias acode -keyalg RSA -keysize 2048 -validity 10000
fi

# cleanup if needed
rm -rf *.apks  toc.pb

# convert to apk
for aab in *.aab; do
java -jar "bundletool-all-1.13.1.jar" build-apks --bundle=$aab --mode=universal --output="${aab%.*}.apks" --ks=acode.keystore --ks-pass=pass:acode1 --ks-key-alias=acode --key-pass=pass:acode1

# extract apk
unzip ${aab%.*}.apks
mv -v universal.apk ${aab%.*}.apk
done
```

**Comment by deadlyjack** [comment]
Hi thanks for the script, but there is not to build free version of the app. Please change the script to only build APK of pro version.

**Comment by deadlyjack** [comment]
Thanks for updating the script. I noticed it's building `.aab` file but I'm not supporting it yet. It needs to build `.apk` for production also.

**Comment by RaSan147** [comment]
any update?? can't build it anyway :( 
your app is really great but the ad on keyboard led me here to build myself and spent hours trying to build this

**Comment by andrewleech** [comment]
> Thanks for updating the script. I noticed it's building `.aab` file but I'm not supporting it yet. It needs to build `.apk` for production also.

aab files are what Cordova always makes now for production builds, are you building with an older version? 

.aab are designed to be submitted to play store where they're signed in then cloud.

I wrote above how I was converting the aab to APK locally for testing, but it needs signing as part of the process. I could copy that process into the github actions but for it to be compatible with your official builds it'd need your signatures store added in a protected way.

I kind of assumed you probably wouldn't want the paid / prod version of the APK too easily available here anyway :-D

**Comment by Sohil876** [comment]
> > Thanks for updating the script. I noticed it's building `.aab` file but I'm not supporting it yet. It needs to build `.apk` for production also.
> 
> aab files are what Cordova always makes now for production builds, are you building with an older version?
> 
> .aab are designed to be submitted to play store where they're signed in then cloud.
> 
> I wrote above how I was converting the aab to APK locally for testing, but it needs signing as part of the process. I could copy that process into the github actions but for it to be compatible with your official builds it'd need your signatures store added in a protected way.
> 
> I kind of assumed you probably wouldn't want the paid / prod version of the APK too easily available here anyway :-D

You dont need to do that, just set `packageType` to apk for your build type in [build.json](https://cordova.apache.org/docs/en/11.x/guide/platforms/android/#using-buildjson) and it'll build apk instead of aab.

**Review by sebastianjnuwu — COMMENTED** [review]
Git.....

**Pull request closed without merging**
